title: ryan dowd | blog
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: '/'
url: 'https://rdowd.com'
site-twitter: '_rdowd'

# Author Settings
author: Ryan Dowd
author-img: ryandowd.jpg
about-author: I work as a blue teamer, and am a macOS security hobbyist. I like to share interesting things that I learn about Apple internals.
social-twitter: _rdowd
social-github: dowdry
social-email: me@rdowd.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
